const routes = {
    home: '/',
    login: '/login',
    register: '/register',
    verifyOTP: '/verification',
    changePassword: '/changePassword',
    userReport: '/report',
    recharge: '/recharge',
    rechargeHistory: '/rechargeHistory',
    statistic: '/statistic',
    userService: '/service',
    dashboard: '/admin/dashboard',
    freelancer: '/admin/freelancer',
    recruiter: '/admin/recruiter',
    staff: '/admin/staff',
    career: '/admin/career',
    subCareer: '/admin/subCareer',
    service: '/admin/service',
    payment: '/admin/payment',
    post: '/admin/post',
    report: '/admin/report',
    viewDetailFreelancerAdmin: '/admin/viewDetailFreelancer',
    viewDetailRecruiterAdmin: '/admin/viewDetailRecruiter',
    viewDetailPostAdmin: '/admin/viewDetailPost',
    freelancerProfile: '/freelancer/profile',
    searchJob: '/freelancer/search',
    jobApply: '/freelancer/jobApply',
    updateFreelancer: '/freelancer/updateProfile',
    viewDetailFreelancer: '/freelancer/viewProfile',
    viewDetailPost: '/freelancer/viewDetailPost',
    recruiterProfile: '/recruiter/profile',
    searchFreelancer: '/recruiter/search',
    postManagement: '/recruiter/postManagement',
    updateRecruiter: '/recruiter/updateProfile',
    postJob: '/recruiter/postJob',
};

export default routes;
