import { createStore } from 'redux';
import * as loginServices from './services/loginServices';

const userId = localStorage.getItem('userId');
console.log(userId);

const initialState = {
    sidebarShow: true,
    account: { role: '' },
    accountBalance: 0,
    accountAvatar: '',
    currentServiceName: null,
    currentServiceId: null,
    isMemberShip: false,
    country: [
        'Canada',
        'Sint Maarten',
        'United States',
        'United States Minor Outlying Islands',
        'Kazakhstan',
        'Egypt',
        'South Africa',
        'Greece',
        'Netherlands',
        'Belgium',
        'France',
        'Spain',
        'Hungary',
        'Holy See (Vatican City State)',
        'Italy',
        'Romania',
        'Switzerland',
        'Austria',
        'Guernsey',
        'Isle of Man',
        'Jersey',
        'United Kingdom',
        'Denmark',
        'Sweden',
        'Norway',
        'Svalbard and Jan Mayen',
        'Poland',
        'Germany',
        'Peru',
        'Mexico',
        'Cuba',
        'Argentina',
        'Brazil',
        'Chile',
        'Colombia',
        'Venezuela',
        'Malaysia',
        'Australia',
        'Christmas Island',
        'Indonesia',
        'Philippines',
        'New Zealand',
        'Singapore',
        'Thailand',
        'Russian Federation',
        'Japan',
        'Korea, Republic of',
        'Việt Nam',
        'China',
        'Turkey',
        'India',
        'Pakistan',
        'Afghanistan',
        'Sri Lanka',
        'Myanmar',
        'Iran, Islamic Republic of',
        'South Sudan',
        'Morocco',
        'Western Sahara',
        'Algeria',
        'Tunisia',
        'Libyan Arab Jamahiriya',
        'Gambia',
        'Senegal',
        'Mauritania',
        'Mali',
        'Guinea',
        'Cote D Ivoire',
        'Burkina Faso',
        'Niger',
        'Togo',
        'Benin',
        'Mauritius',
        'Liberia',
        'Sierra Leone',
        'Ghana',
        'Nigeria',
        'Chad',
        'Central African Republic',
        'Cameroon',
        'Cape Verde',
        'Sao Tome and Principe',
        'Equatorial Guinea',
        'Gabon',
        'Congo',
        'Congo, the Democratic Republic of the',
        'Angola',
        'Guinea-Bissau',
        'British Indian Ocean Territory',
        'Seychelles',
        'Sudan',
        'Rwanda',
        'Ethiopia',
        'Somalia',
        'Djibouti',
        'Kenya',
        'Tanzania, United Republic of',
        'Uganda',
        'Burundi',
        'Mozambique',
        'Zambia',
        'Madagascar',
        'Reunion',
        'Zimbabwe',
        'Namibia',
        'Malawi',
        'Lesotho',
        'Botswana',
        'Swaziland',
        'Comoros',
        'Mayotte',
        'Saint Helena',
        'Eritrea',
        'Aruba',
        'Faroe Islands',
        'Greenland',
        'Gibraltar',
        'Portugal',
        'Luxembourg',
        'Ireland',
        'Iceland',
        'Albania',
        'Malta',
        'Cyprus',
        'Aland Islands',
        'Finland',
        'Bulgaria',
        'Lithuania',
        'Latvia',
        'Estonia',
        'Moldova, Republic of',
        'Armenia',
        'Belarus',
        'Andorra',
        'Monaco',
        'San Marino',
        'Ukraine',
        'Kosovo',
        'Serbia',
        'Serbia and Montenegro',
        'Montenegro',
        'Croatia',
        'Slovenia',
        'Bosnia and Herzegovina',
        'Macedonia, the Former Yugoslav Republic of',
        'Czech Republic',
        'Slovakia',
        'Liechtenstein',
        'Falkland Islands (Malvinas)',
        'Belize',
        'Guatemala',
        'El Salvador',
        'Honduras',
        'Nicaragua',
        'Costa Rica',
        'Panama',
        'Saint Pierre and Miquelon',
        'Haiti',
        'Guadeloupe',
        'Saint Barthelemy',
        'Saint Martin',
        'Bolivia',
        'Guyana',
        'Ecuador',
        'French Guiana',
        'Paraguay',
        'Martinique',
        'Suriname',
        'Uruguay',
        'Bonaire, Sint Eustatius and Saba',
        'Curacao',
        'Netherlands Antilles',
        'Timor-Leste',
        'Cocos (Keeling) Islands',
        'Norfolk Island',
        'Brunei Darussalam',
        'Nauru',
        'Papua New Guinea',
        'Tonga',
        'Solomon Islands',
        'Vanuatu',
        'Fiji',
        'Palau',
        'Wallis and Futuna',
        'Cook Islands',
        'Niue',
        'Samoa',
        'Kiribati',
        'New Caledonia',
        'Tuvalu',
        'French Polynesia',
        'Tokelau',
        'Micronesia, Federated States of',
        'Marshall Islands',
        'Korea, Democratic Peoples Republic of',
        'Hong Kong',
        'Macao',
        'Cambodia',
        'Lao Peoples Democratic Republic',
        'Bangladesh',
        'Taiwan, Province of China',
        'Maldives',
        'Lebanon',
        'Jordan',
        'Syrian Arab Republic',
        'Iraq',
        'Kuwait',
        'Saudi Arabia',
        'Yemen',
        'Oman',
        'Palestinian Territory, Occupied',
        'United Arab Emirates',
        'Israel',
        'Bahrain',
        'Qatar',
        'Bhutan',
        'Mongolia',
        'Nepal',
        'Tajikistan',
        'Azerbaijan',
        'Georgia',
        'Kyrgyzstan',
        'Uzbekistan',
        'Bahamas',
        'Barbados',
        'Anguilla',
        'Antigua and Barbuda',
        'Virgin Islands, British',
        'Virgin Islands, U.s.',
        'Cayman Islands',
        'Bermuda',
        'Grenada',
        'Turks and Caicos Islands',
        'Montserrat',
        'Northern Mariana Islands',
        'Guam',
        'American Samoa',
        'Saint Lucia',
        'Dominica',
        'Saint Vincent and the Grenadines',
        'Puerto Rico',
        'Dominican Republic',
        'Trinidad and Tobago',
        'Saint Kitts and Nevis',
        'Jamaica',
    ],
    city: [
        'Hồ Chí Minh',
        'Đà Nẵng',
        'An Giang',
        'Bà Rịa - Vũng Tàu ',
        'Bắc Cạn ',
        'Bắc Giang ',
        'Bạc Liêu ',
        'Bắc Ninh ',
        'Bến Tre ',
        'Bình Định ',
        'Bình Dương ',
        'Bình Phước ',
        'Bình Thuận ',
        'Cà Mau ',
        'Cần Thơ ',
        'Cao Bằng ',
        'Đắk Lắk ',
        'Đắk Nông ',
        'Điện Biên ',
        'Hà Nội',
        'Khánh Hòa',
        'Đồng Nai ',
        'Đồng Tháp ',
        'Gia Lai ',
        'Hà Giang ',
        'Hà Nam ',
        'Hà Tĩnh ',
        'Hải Dương ',
        'Hải Phòng ',
        'Hậu Giang ',
        'Hòa Bình ',
        'Hưng Yên ',
        'Kiên Giang ',
        'Kon Tum ',
        'Lai Châu ',
        'Lâm Đồng ',
        'Lạng Sơn ',
        'Lào Cai ',
        'Long An  ',
        'Nam Định ',
        'Nghệ An ',
        'Ninh Bình ',
        'Ninh Thuận ',
        'Phú Thọ ',
        'Phú Yên ',
        'Quảng Bình ',
        'Quảng Nam ',
        'Quảng Ngãi ',
        'Quảng Ninh ',
        'Quảng Trị ',
        'Sóc Trăng ',
        'Sơn La  ',
        'Tây Ninh ',
        'Thái Bình ',
        'Thái Nguyên ',
        'Thanh Hóa ',
        'Thừa Thiên Huế ',
        'Tiền Giang ',
        'Trà Vinh ',
        'Tuyên Quang ',
        'Vĩnh Long ',
        'Vĩnh Phúc ',
    ],
};
const fetchApi = async (userId) => {
    const result = await loginServices.getInfoUser(userId);
    console.log(result);
    if (typeof result === 'object') {
        initialState.account = result;
        initialState.accountBalance = result.accountBalance;
        initialState.accountAvatar = result.avatar;
        initialState.currentServiceName = result.currentServiceName;
        initialState.currentServiceId = result.currentServiceId;
        initialState.isMemberShip = result.isMemberShip;
    }
};
if (userId !== null) {
    fetchApi(userId);
}
const changeState = (state = initialState, { type, ...rest }) => {
    switch (type) {
        case 'set':
            return { ...state, ...rest };
        default:
            return state;
    }
};

const store = createStore(changeState);
export default store;
